import type { CheckAnnotation, GitHubClient } from "./github-client";
import type { Finding, ReviewResponse } from "./schema";

export const COMMENT_MARKER = "<!-- friendlyai-review-action:v1 -->";

const ANNOTATION_LEVEL: Record<
  Finding["severity"],
  "notice" | "warning" | "failure"
> = {
  info: "notice",
  low: "notice",
  medium: "warning",
  high: "failure",
  critical: "failure",
};

interface RenderCommentArgs {
  response: ReviewResponse;
  runUrl: string;
  fileCount: number;
  truncated: boolean;
  omittedFiles: string[];
}

export function renderComment(args: RenderCommentArgs): string {
  const { response, runUrl, fileCount, truncated, omittedFiles } = args;
  const lines: string[] = [];

  lines.push(COMMENT_MARKER);
  lines.push("");
  lines.push("## FriendlyAI Review result");
  lines.push("");
  lines.push(`**${response.reason}**`);
  if (response.summary) {
    lines.push("");
    lines.push(response.summary);
  }
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|---|---|");
  lines.push(`| Conclusion | \`${response.conclusion}\` |`);
  lines.push(`| Max risk | \`${response.maxRisk ?? "unknown"}\` |`);
  lines.push(`| Findings | ${response.findings.length} |`);
  lines.push(`| Files reviewed | ${fileCount}${truncated ? " (diff truncated)" : ""} |`);
  if (response.reportUrl) {
    lines.push(`| Report | ${response.reportUrl} |`);
  }
  lines.push("");

  if (response.findings.length === 0) {
    lines.push("_No findings returned._");
  } else {
    lines.push("### Findings");
    lines.push("");
    lines.push("| Severity | File | Line | Issue | Suggestion |");
    lines.push("|---|---|---|---|---|");
    for (const finding of response.findings) {
      lines.push(
        `| \`${finding.severity}\` | ${
          finding.file ? `\`${escapeCell(finding.file)}\`` : "-"
        } | ${finding.line ?? "-"} | ${escapeCell(finding.issue)} | ${escapeCell(
          finding.suggestion,
        )} |`,
      );
    }
  }

  if (omittedFiles.length > 0) {
    lines.push("");
    lines.push("### Omitted diffs");
    lines.push("");
    lines.push(
      "Some patches were omitted from the request because of the configured diff budget.",
    );
    for (const file of omittedFiles.slice(0, 50)) {
      lines.push(`- \`${escapeCell(file)}\``);
    }
    if (omittedFiles.length > 50) {
      lines.push(`- ...and ${omittedFiles.length - 50} more`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`_Generated by [FriendlyAI Review](${runUrl})._`);

  return lines.join("\n");
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

export interface PostCommentArgs {
  githubClient: GitHubClient;
  owner: string;
  repo: string;
  prNumber: number;
  body: string;
}

export async function postOrUpdateComment(
  args: PostCommentArgs,
): Promise<string> {
  const { githubClient, owner, repo, prNumber, body } = args;

  let existingId: number | null = null;
  for (let page = 1; page <= 10; page += 1) {
    const data = await githubClient.listIssueComments(owner, repo, prNumber, page);
    const match = data.find((comment) =>
      comment.body?.includes(COMMENT_MARKER),
    );
    if (match) {
      existingId = match.id;
      break;
    }
    if (data.length < 100) break;
  }

  if (existingId !== null) {
    const data = await githubClient.updateIssueComment(
      owner,
      repo,
      existingId,
      body,
    );
    return data.html_url;
  }

  const data = await githubClient.createIssueComment(
    owner,
    repo,
    prNumber,
    body,
  );
  return data.html_url;
}

export interface PostCheckArgs {
  githubClient: GitHubClient;
  owner: string;
  repo: string;
  headSha: string;
  conclusion: ReviewResponse["conclusion"];
  title: string;
  summary: string;
  details?: string;
  findings?: Finding[];
}

export async function postCheckRun(args: PostCheckArgs): Promise<string> {
  const {
    githubClient,
    owner,
    repo,
    headSha,
    conclusion,
    title,
    summary,
    details,
    findings = [],
  } = args;

  const annotations = findingsToAnnotations(findings);
  return githubClient.createCheckRun({
    owner,
    repo,
    headSha,
    conclusion,
    title: truncate(title, 255),
    summary,
    details,
    annotations,
  });
}

function findingsToAnnotations(findings: Finding[]): CheckAnnotation[] {
  return findings
    .filter((finding) => finding.file && finding.line)
    .slice(0, 50)
    .map((finding) => ({
      path: finding.file as string,
      start_line: finding.line as number,
      end_line: finding.line as number,
      annotation_level: ANNOTATION_LEVEL[finding.severity],
      message: truncate(finding.issue, 64000),
      title: truncate(`${finding.severity}: ${finding.issue}`, 255),
      raw_details: truncate(finding.suggestion, 64000),
    }));
}

function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) return value;
  return `${value.slice(0, Math.max(0, maxLength - 3))}...`;
}
